### ISSUE TITLE
some problems in cospar doc 

### ISSUE THREAD

**Issue by DC-Jade** [ShouWenWang-Lab/cospar#1]
- API/Plotting/[pl.fate_hierarchy]_(https://cospar.readthedocs.io/en/latest/cospar.pl.fate_hierarchy.html) annotation_ could be wrong

- Error: there is no _"selected_times"_ argument in TUTORIAL/Preprocessing/Refine state annotation by marker genes/[cs.pp.refine_state_info_by_marker_genes](https://cospar.readthedocs.io/en/latest/20211010_preprocessing.html?highlight=selected_times%20refine#Refine-state-annotation-by-marker-genes) method of cospar 0.3.0 (python 3.9.16)

**Comment by ShouWenWang** [comment]
Sorry. Just saw this.

Will fix the second error due to our recent update. For the first error, could you explain more? I did not get it.

**Comment by DC-Jade** [comment]
I mean that **_both pl.fate_couping and pl.fate_hierarchy_** have the _same function annotation_.
