### ISSUE TITLE
DARLIN data not accessible

### ISSUE THREAD

**Issue by LouisFaure** [ShouWenWang-Lab/cospar#8]
Hi, I would like to reproduce the notebook focusing on DARLIN data, however, I cannot download the anndata. Could you enable access to it?

Many thanks!

**Comment by ShouWenWang** [comment]
Sorry, there are some issue  with our downloading server. Here is a link that can download the file for now. We will fix this problem soon. 

https://westlakeu-my.sharepoint.com/:u:/g/personal/wangshouwen_westlake_edu_cn/ETiN1opaD-lFsmUOelCqXcEBU3tGJNNtdnYCREtMDqUqfA?e=BzHhr3

Once downloading the file, just run this command to load the adata
```python
cs.hf.read('path/to/tissue_adata_refined_20221106_joint.h5ad')
```

**Comment by ShouWenWang** [comment]
Data downloading has been fixed. Please use the latest cospar code.

**Comment by zsteve** [comment]
FYI I tried to use the same function from the current github version of cospar (I installed using pip install from git). I got a 404 error from the westlake server.

**Comment by ShouWenWang** [comment]
We will fix it. There is also a download link in the notebook. That should work

 ――
Shou-Wen Wang, PhD
Principal Investigator
School of Life Sciences | School of Sciences
Westlake University
Shilongshan ST #18, Xihu, Hangzhou, Zhejiang
https://www.shouwenwang-lab.com/


________________________________

**Comment by ShouWenWang** [comment]
It is fixed in the latest CoSpar commit.
