### ISSUE TITLE
URL error issue

### ISSUE THREAD

**Issue by Zhklu2003** [ShouWenWang-Lab/cospar#9]
I have downloaded the package and try below 2 lines of codes:

import cospar as cs
adata_orig = cs.datasets.hematopoiesis()

Then I get this URL error. 

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

Could you give me some advice? Thanks.

**Comment by ShouWenWang** [comment]
Sorry for the inconvenience. We are working to resolve the issue. At the same time, you can use the following links to directly download the data. 
----------------------------------------------------
DARLIN data (Li et.al., 2023)
https://westlakeu-my.sharepoint.com/:u:/g/personal/wangshouwen_westlake_edu_cn/ETiN1opaD-lFsmUOelCqXcEBU3tGJNNtdnYCREtMDqUqfA?e=vx7Ubt

Reprogramming dataset (Biddy et.al. 2018)
https://westlakeu-my.sharepoint.com/:u:/g/personal/wangshouwen_westlake_edu_cn/EZULpRrsdZJKtxlYz_hZpI4BcNwEtu26K1DVhWhSO32ONQ?e=hO2cdW

Hematopoietic (LARRY) datasets with only clonally labeled cells (Weinreb et.al., 2020)
https://westlakeu-my.sharepoint.com/:u:/g/personal/wangshouwen_westlake_edu_cn/ERmTryFAw7pPnABBZWNdhJUBe2UDfOIEpYBeU4qTcq7Nfg?e=LeGFGW

Sub-sampled hematopoietic (LARRY) datasets with only clonally labeled cells (Weinreb et.al., 2020)
https://westlakeu-my.sharepoint.com/:u:/g/personal/wangshouwen_westlake_edu_cn/EaaQVF4tg4dMitqmjgKkHMYBm06PCs6K6D-ZAm0WGX4KZA?e=Ht48On

Lung dataset
https://westlakeu-my.sharepoint.com/:u:/g/personal/wangshouwen_westlake_edu_cn/EaD0r9Rd6NdGrVyhEnAO8KEB40YzdiePvPRjd1jtEY6evQ?e=rTJhSf

**Comment by Zhklu2003** [comment]
Thanks!

**Comment by ShouWenWang** [comment]
Problem fixed in the latest cospar on the github.
